spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nr31db
    username: postgres
    password: password

logging:
  level:
    org.springframework.web: INFO
    org.nr31.backend: DEBUG

jwt:
  secret: sEsXIiICXqeaAiZ+45aWoZhHMXf2hj2dpq0CZQfIGPo=
  expiration: 600000
