spring:
  profiles:
    active: prod
  application:
    name: nr31-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
        javax:
          cache:
            provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
            missing_cache_strategy: create
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=1h

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  security:
    user:
      name: user
      password: password

logging:
  level:
    org.springframework.web: INFO
    org.nr31.backend: INFO
  file:
    name: /app/logs/application.log
logback:
  rollingpolicy:
    file-name-pattern: /app/logs/application-%d{yyyy-MM-dd}.%i.log
    max-history: 14
    max-file-size: 10MB
    total-size-cap: 1GB

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  openapi:
    info:
      title: Nr.31 FKR API
      version: 1.0.0
      description: This is the backend for Nr.31 FKR site.

app:
  discord:
    bot-token: ${DISCORD_BOT_TOKEN}
